#!/usr/bin/env bash
COMMAND=cp
ROOT=/Users/sraghuram/myws/3x/MatGSA/neo4j 
SOURCE=$ROOT/community/kernel/src/main/java
DEST=$ROOT/community/neo4j-store-API/src/main/java
--rsync -a --include '*/' --exclude '*' "$SOURCE/" "$DEST"
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/StorageEngine.java $DEST/org/neo4j/storageengine/api/StorageEngine.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/StorageEngine.java $DEST/org/neo4j/storageengine/api/StorageEngine.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/StorageReader.java $DEST/org/neo4j/storageengine/api/StorageReader.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/StorageReader.java $DEST/org/neo4j/storageengine/api/StorageReader.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/TransactionalDependencies.java $DEST/org/neo4j/storageengine/api/TransactionalDependencies.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/TransactionalDependencies.java $DEST/org/neo4j/storageengine/api/TransactionalDependencies.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/txstate/TxStateHolder.java $DEST/org/neo4j/kernel/api/txstate/TxStateHolder.java
$COMMAND $SOURCE/org/neo4j/kernel/api/txstate/TxStateHolder.java $DEST/org/neo4j/kernel/api/txstate/TxStateHolder.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/txstate/TransactionState.java $DEST/org/neo4j/kernel/api/txstate/TransactionState.java
$COMMAND $SOURCE/org/neo4j/kernel/api/txstate/TransactionState.java $DEST/org/neo4j/kernel/api/txstate/TransactionState.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/index/SchemaIndexDescriptor.java $DEST/org/neo4j/kernel/api/schema/index/SchemaIndexDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/index/SchemaIndexDescriptor.java $DEST/org/neo4j/kernel/api/schema/index/SchemaIndexDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/IndexBackedConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/IndexBackedConstraintDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/IndexBackedConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/IndexBackedConstraintDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/ConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/ConstraintDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/ConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/ConstraintDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/index/SchemaIndexDescriptorFactory.java $DEST/org/neo4j/kernel/api/schema/index/SchemaIndexDescriptorFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/index/SchemaIndexDescriptorFactory.java $DEST/org/neo4j/kernel/api/schema/index/SchemaIndexDescriptorFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/SchemaDescriptorFactory.java $DEST/org/neo4j/kernel/api/schema/SchemaDescriptorFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/SchemaDescriptorFactory.java $DEST/org/neo4j/kernel/api/schema/SchemaDescriptorFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/LabelSchemaDescriptor.java $DEST/org/neo4j/kernel/api/schema/LabelSchemaDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/LabelSchemaDescriptor.java $DEST/org/neo4j/kernel/api/schema/LabelSchemaDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/locking/ResourceTypes.java $DEST/org/neo4j/kernel/impl/locking/ResourceTypes.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/locking/ResourceTypes.java $DEST/org/neo4j/kernel/impl/locking/ResourceTypes.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/util/concurrent/LockWaitStrategies.java $DEST/org/neo4j/kernel/impl/util/concurrent/LockWaitStrategies.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/util/concurrent/LockWaitStrategies.java $DEST/org/neo4j/kernel/impl/util/concurrent/LockWaitStrategies.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/lock/AcquireLockTimeoutException.java $DEST/org/neo4j/storageengine/api/lock/AcquireLockTimeoutException.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/lock/AcquireLockTimeoutException.java $DEST/org/neo4j/storageengine/api/lock/AcquireLockTimeoutException.java
echo $COMMAND $SOURCE/org/neo4j/helpers/Strings.java $DEST/org/neo4j/helpers/Strings.java
$COMMAND $SOURCE/org/neo4j/helpers/Strings.java $DEST/org/neo4j/helpers/Strings.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/RelationTypeSchemaDescriptor.java $DEST/org/neo4j/kernel/api/schema/RelationTypeSchemaDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/RelationTypeSchemaDescriptor.java $DEST/org/neo4j/kernel/api/schema/RelationTypeSchemaDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/ReadableTransactionState.java $DEST/org/neo4j/storageengine/api/txstate/ReadableTransactionState.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/ReadableTransactionState.java $DEST/org/neo4j/storageengine/api/txstate/ReadableTransactionState.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/TxStateVisitor.java $DEST/org/neo4j/storageengine/api/txstate/TxStateVisitor.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/TxStateVisitor.java $DEST/org/neo4j/storageengine/api/txstate/TxStateVisitor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/schema/CreateConstraintFailureException.java $DEST/org/neo4j/kernel/api/exceptions/schema/CreateConstraintFailureException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/schema/CreateConstraintFailureException.java $DEST/org/neo4j/kernel/api/exceptions/schema/CreateConstraintFailureException.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/LongDiffSets.java $DEST/org/neo4j/storageengine/api/txstate/LongDiffSets.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/LongDiffSets.java $DEST/org/neo4j/storageengine/api/txstate/LongDiffSets.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/RelationshipVisitor.java $DEST/org/neo4j/kernel/impl/api/RelationshipVisitor.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/RelationshipVisitor.java $DEST/org/neo4j/kernel/impl/api/RelationshipVisitor.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/ReadableDiffSets.java $DEST/org/neo4j/storageengine/api/txstate/ReadableDiffSets.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/ReadableDiffSets.java $DEST/org/neo4j/storageengine/api/txstate/ReadableDiffSets.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/SuperReadableDiffSets.java $DEST/org/neo4j/storageengine/api/txstate/SuperReadableDiffSets.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/SuperReadableDiffSets.java $DEST/org/neo4j/storageengine/api/txstate/SuperReadableDiffSets.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/DiffSetsVisitor.java $DEST/org/neo4j/storageengine/api/txstate/DiffSetsVisitor.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/DiffSetsVisitor.java $DEST/org/neo4j/storageengine/api/txstate/DiffSetsVisitor.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/NodeState.java $DEST/org/neo4j/storageengine/api/txstate/NodeState.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/NodeState.java $DEST/org/neo4j/storageengine/api/txstate/NodeState.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/newapi/RelationshipDirection.java $DEST/org/neo4j/kernel/impl/newapi/RelationshipDirection.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/newapi/RelationshipDirection.java $DEST/org/neo4j/kernel/impl/newapi/RelationshipDirection.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/PropertyContainerState.java $DEST/org/neo4j/storageengine/api/txstate/PropertyContainerState.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/PropertyContainerState.java $DEST/org/neo4j/storageengine/api/txstate/PropertyContainerState.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/StorageProperty.java $DEST/org/neo4j/storageengine/api/StorageProperty.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/StorageProperty.java $DEST/org/neo4j/storageengine/api/StorageProperty.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/RelationshipState.java $DEST/org/neo4j/storageengine/api/txstate/RelationshipState.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/txstate/RelationshipState.java $DEST/org/neo4j/storageengine/api/txstate/RelationshipState.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/state/GraphState.java $DEST/org/neo4j/kernel/impl/api/state/GraphState.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/state/GraphState.java $DEST/org/neo4j/kernel/impl/api/state/GraphState.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/state/PropertyContainerStateImpl.java $DEST/org/neo4j/kernel/impl/api/state/PropertyContainerStateImpl.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/state/PropertyContainerStateImpl.java $DEST/org/neo4j/kernel/impl/api/state/PropertyContainerStateImpl.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/properties/PropertyKeyValue.java $DEST/org/neo4j/kernel/api/properties/PropertyKeyValue.java
$COMMAND $SOURCE/org/neo4j/kernel/api/properties/PropertyKeyValue.java $DEST/org/neo4j/kernel/api/properties/PropertyKeyValue.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/txstate/ExplicitIndexTransactionState.java $DEST/org/neo4j/kernel/api/txstate/ExplicitIndexTransactionState.java
$COMMAND $SOURCE/org/neo4j/kernel/api/txstate/ExplicitIndexTransactionState.java $DEST/org/neo4j/kernel/api/txstate/ExplicitIndexTransactionState.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/ExplicitIndex.java $DEST/org/neo4j/kernel/api/ExplicitIndex.java
$COMMAND $SOURCE/org/neo4j/kernel/api/ExplicitIndex.java $DEST/org/neo4j/kernel/api/ExplicitIndex.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/ExplicitIndexHits.java $DEST/org/neo4j/kernel/api/ExplicitIndexHits.java
$COMMAND $SOURCE/org/neo4j/kernel/api/ExplicitIndexHits.java $DEST/org/neo4j/kernel/api/ExplicitIndexHits.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/index/IndexEntityType.java $DEST/org/neo4j/kernel/impl/index/IndexEntityType.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/index/IndexEntityType.java $DEST/org/neo4j/kernel/impl/index/IndexEntityType.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/state/RecordState.java $DEST/org/neo4j/kernel/impl/transaction/state/RecordState.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/state/RecordState.java $DEST/org/neo4j/kernel/impl/transaction/state/RecordState.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/AssertOpen.java $DEST/org/neo4j/kernel/api/AssertOpen.java
$COMMAND $SOURCE/org/neo4j/kernel/api/AssertOpen.java $DEST/org/neo4j/kernel/api/AssertOpen.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/CommandCreationContext.java $DEST/org/neo4j/storageengine/api/CommandCreationContext.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/CommandCreationContext.java $DEST/org/neo4j/storageengine/api/CommandCreationContext.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/lock/ResourceLocker.java $DEST/org/neo4j/storageengine/api/lock/ResourceLocker.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/lock/ResourceLocker.java $DEST/org/neo4j/storageengine/api/lock/ResourceLocker.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/locking/LockTracer.java $DEST/org/neo4j/kernel/impl/locking/LockTracer.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/locking/LockTracer.java $DEST/org/neo4j/kernel/impl/locking/LockTracer.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/locking/LockWaitEvent.java $DEST/org/neo4j/kernel/impl/locking/LockWaitEvent.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/locking/LockWaitEvent.java $DEST/org/neo4j/kernel/impl/locking/LockWaitEvent.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/locking/CombinedTracer.java $DEST/org/neo4j/kernel/impl/locking/CombinedTracer.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/locking/CombinedTracer.java $DEST/org/neo4j/kernel/impl/locking/CombinedTracer.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/CommandsToApply.java $DEST/org/neo4j/storageengine/api/CommandsToApply.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/CommandsToApply.java $DEST/org/neo4j/storageengine/api/CommandsToApply.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/CommandStream.java $DEST/org/neo4j/storageengine/api/CommandStream.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/CommandStream.java $DEST/org/neo4j/storageengine/api/CommandStream.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/TransactionApplicationMode.java $DEST/org/neo4j/storageengine/api/TransactionApplicationMode.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/TransactionApplicationMode.java $DEST/org/neo4j/storageengine/api/TransactionApplicationMode.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/command/Command.java $DEST/org/neo4j/kernel/impl/transaction/command/Command.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/command/Command.java $DEST/org/neo4j/kernel/impl/transaction/command/Command.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/AbstractBaseRecord.java $DEST/org/neo4j/kernel/impl/store/record/AbstractBaseRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/AbstractBaseRecord.java $DEST/org/neo4j/kernel/impl/store/record/AbstractBaseRecord.java
echo $COMMAND $SOURCE/org/neo4j/helpers/CloneableInPublic.java $DEST/org/neo4j/helpers/CloneableInPublic.java
$COMMAND $SOURCE/org/neo4j/helpers/CloneableInPublic.java $DEST/org/neo4j/helpers/CloneableInPublic.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/CommandVisitor.java $DEST/org/neo4j/kernel/impl/api/CommandVisitor.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/CommandVisitor.java $DEST/org/neo4j/kernel/impl/api/CommandVisitor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/index/IndexCommand.java $DEST/org/neo4j/kernel/impl/index/IndexCommand.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/index/IndexCommand.java $DEST/org/neo4j/kernel/impl/index/IndexCommand.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/WritableChannel.java $DEST/org/neo4j/storageengine/api/WritableChannel.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/WritableChannel.java $DEST/org/neo4j/storageengine/api/WritableChannel.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/util/IoPrimitiveUtils.java $DEST/org/neo4j/kernel/impl/util/IoPrimitiveUtils.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/util/IoPrimitiveUtils.java $DEST/org/neo4j/kernel/impl/util/IoPrimitiveUtils.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/ReadableChannel.java $DEST/org/neo4j/storageengine/api/ReadableChannel.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/ReadableChannel.java $DEST/org/neo4j/storageengine/api/ReadableChannel.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/index/IndexDefineCommand.java $DEST/org/neo4j/kernel/impl/index/IndexDefineCommand.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/index/IndexDefineCommand.java $DEST/org/neo4j/kernel/impl/index/IndexDefineCommand.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/NodeRecord.java $DEST/org/neo4j/kernel/impl/store/record/NodeRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/NodeRecord.java $DEST/org/neo4j/kernel/impl/store/record/NodeRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/PropertyRecord.java $DEST/org/neo4j/kernel/impl/store/record/PropertyRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/PropertyRecord.java $DEST/org/neo4j/kernel/impl/store/record/PropertyRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/PrimitiveRecord.java $DEST/org/neo4j/kernel/impl/store/record/PrimitiveRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/PrimitiveRecord.java $DEST/org/neo4j/kernel/impl/store/record/PrimitiveRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/Record.java $DEST/org/neo4j/kernel/impl/store/record/Record.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/Record.java $DEST/org/neo4j/kernel/impl/store/record/Record.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/DynamicRecord.java $DEST/org/neo4j/kernel/impl/store/record/DynamicRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/DynamicRecord.java $DEST/org/neo4j/kernel/impl/store/record/DynamicRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/PropertyType.java $DEST/org/neo4j/kernel/impl/store/PropertyType.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/PropertyType.java $DEST/org/neo4j/kernel/impl/store/PropertyType.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/PropertyBlock.java $DEST/org/neo4j/kernel/impl/store/record/PropertyBlock.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/PropertyBlock.java $DEST/org/neo4j/kernel/impl/store/record/PropertyBlock.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/PropertyStore.java $DEST/org/neo4j/kernel/impl/store/PropertyStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/PropertyStore.java $DEST/org/neo4j/kernel/impl/store/PropertyStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/Config.java $DEST/org/neo4j/kernel/configuration/Config.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/Config.java $DEST/org/neo4j/kernel/configuration/Config.java
echo $COMMAND $SOURCE/org/neo4j/kernel/info/DiagnosticsPhase.java $DEST/org/neo4j/kernel/info/DiagnosticsPhase.java
$COMMAND $SOURCE/org/neo4j/kernel/info/DiagnosticsPhase.java $DEST/org/neo4j/kernel/info/DiagnosticsPhase.java
echo $COMMAND $SOURCE/org/neo4j/kernel/info/DiagnosticsProvider.java $DEST/org/neo4j/kernel/info/DiagnosticsProvider.java
$COMMAND $SOURCE/org/neo4j/kernel/info/DiagnosticsProvider.java $DEST/org/neo4j/kernel/info/DiagnosticsProvider.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/ConfigurationValidator.java $DEST/org/neo4j/kernel/configuration/ConfigurationValidator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/ConfigurationValidator.java $DEST/org/neo4j/kernel/configuration/ConfigurationValidator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/BoltConnector.java $DEST/org/neo4j/kernel/configuration/BoltConnector.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/BoltConnector.java $DEST/org/neo4j/kernel/configuration/BoltConnector.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/Connector.java $DEST/org/neo4j/kernel/configuration/Connector.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/Connector.java $DEST/org/neo4j/kernel/configuration/Connector.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/GroupSettingSupport.java $DEST/org/neo4j/kernel/configuration/GroupSettingSupport.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/GroupSettingSupport.java $DEST/org/neo4j/kernel/configuration/GroupSettingSupport.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/Group.java $DEST/org/neo4j/kernel/configuration/Group.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/Group.java $DEST/org/neo4j/kernel/configuration/Group.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/Settings.java $DEST/org/neo4j/kernel/configuration/Settings.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/Settings.java $DEST/org/neo4j/kernel/configuration/Settings.java
echo $COMMAND $SOURCE/org/neo4j/helpers/HostnamePort.java $DEST/org/neo4j/helpers/HostnamePort.java
$COMMAND $SOURCE/org/neo4j/helpers/HostnamePort.java $DEST/org/neo4j/helpers/HostnamePort.java
echo $COMMAND $SOURCE/org/neo4j/helpers/TimeUtil.java $DEST/org/neo4j/helpers/TimeUtil.java
$COMMAND $SOURCE/org/neo4j/helpers/TimeUtil.java $DEST/org/neo4j/helpers/TimeUtil.java
echo $COMMAND $SOURCE/org/neo4j/helpers/ListenSocketAddress.java $DEST/org/neo4j/helpers/ListenSocketAddress.java
$COMMAND $SOURCE/org/neo4j/helpers/ListenSocketAddress.java $DEST/org/neo4j/helpers/ListenSocketAddress.java
echo $COMMAND $SOURCE/org/neo4j/helpers/SocketAddress.java $DEST/org/neo4j/helpers/SocketAddress.java
$COMMAND $SOURCE/org/neo4j/helpers/SocketAddress.java $DEST/org/neo4j/helpers/SocketAddress.java
echo $COMMAND $SOURCE/org/neo4j/helpers/SocketAddressParser.java $DEST/org/neo4j/helpers/SocketAddressParser.java
$COMMAND $SOURCE/org/neo4j/helpers/SocketAddressParser.java $DEST/org/neo4j/helpers/SocketAddressParser.java
echo $COMMAND $SOURCE/org/neo4j/helpers/AdvertisedSocketAddress.java $DEST/org/neo4j/helpers/AdvertisedSocketAddress.java
$COMMAND $SOURCE/org/neo4j/helpers/AdvertisedSocketAddress.java $DEST/org/neo4j/helpers/AdvertisedSocketAddress.java
echo $COMMAND $SOURCE/org/neo4j/graphdb/factory/GraphDatabaseSettings.java $DEST/org/neo4j/graphdb/factory/GraphDatabaseSettings.java
$COMMAND $SOURCE/org/neo4j/graphdb/factory/GraphDatabaseSettings.java $DEST/org/neo4j/graphdb/factory/GraphDatabaseSettings.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/GraphDatabaseConfigurationMigrator.java $DEST/org/neo4j/kernel/configuration/GraphDatabaseConfigurationMigrator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/GraphDatabaseConfigurationMigrator.java $DEST/org/neo4j/kernel/configuration/GraphDatabaseConfigurationMigrator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/BaseConfigurationMigrator.java $DEST/org/neo4j/kernel/configuration/BaseConfigurationMigrator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/BaseConfigurationMigrator.java $DEST/org/neo4j/kernel/configuration/BaseConfigurationMigrator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/ConfigurationMigrator.java $DEST/org/neo4j/kernel/configuration/ConfigurationMigrator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/ConfigurationMigrator.java $DEST/org/neo4j/kernel/configuration/ConfigurationMigrator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/BoltConnectorValidator.java $DEST/org/neo4j/kernel/configuration/BoltConnectorValidator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/BoltConnectorValidator.java $DEST/org/neo4j/kernel/configuration/BoltConnectorValidator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/ConnectorValidator.java $DEST/org/neo4j/kernel/configuration/ConnectorValidator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/ConnectorValidator.java $DEST/org/neo4j/kernel/configuration/ConnectorValidator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/ssl/SslPolicyConfigValidator.java $DEST/org/neo4j/kernel/configuration/ssl/SslPolicyConfigValidator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/ssl/SslPolicyConfigValidator.java $DEST/org/neo4j/kernel/configuration/ssl/SslPolicyConfigValidator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/ssl/SslPolicyConfig.java $DEST/org/neo4j/kernel/configuration/ssl/SslPolicyConfig.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/ssl/SslPolicyConfig.java $DEST/org/neo4j/kernel/configuration/ssl/SslPolicyConfig.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/HttpConnectorValidator.java $DEST/org/neo4j/kernel/configuration/HttpConnectorValidator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/HttpConnectorValidator.java $DEST/org/neo4j/kernel/configuration/HttpConnectorValidator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/HttpConnector.java $DEST/org/neo4j/kernel/configuration/HttpConnector.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/HttpConnector.java $DEST/org/neo4j/kernel/configuration/HttpConnector.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/ServerConfigurationValidator.java $DEST/org/neo4j/kernel/configuration/ServerConfigurationValidator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/ServerConfigurationValidator.java $DEST/org/neo4j/kernel/configuration/ServerConfigurationValidator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/util/CopyOnWriteHashMap.java $DEST/org/neo4j/kernel/impl/util/CopyOnWriteHashMap.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/util/CopyOnWriteHashMap.java $DEST/org/neo4j/kernel/impl/util/CopyOnWriteHashMap.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/AnnotationBasedConfigurationMigrator.java $DEST/org/neo4j/kernel/configuration/AnnotationBasedConfigurationMigrator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/AnnotationBasedConfigurationMigrator.java $DEST/org/neo4j/kernel/configuration/AnnotationBasedConfigurationMigrator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/Migrator.java $DEST/org/neo4j/kernel/configuration/Migrator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/Migrator.java $DEST/org/neo4j/kernel/configuration/Migrator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/IndividualSettingsValidator.java $DEST/org/neo4j/kernel/configuration/IndividualSettingsValidator.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/IndividualSettingsValidator.java $DEST/org/neo4j/kernel/configuration/IndividualSettingsValidator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdGeneratorFactory.java $DEST/org/neo4j/kernel/impl/store/id/IdGeneratorFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdGeneratorFactory.java $DEST/org/neo4j/kernel/impl/store/id/IdGeneratorFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdType.java $DEST/org/neo4j/kernel/impl/store/id/IdType.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdType.java $DEST/org/neo4j/kernel/impl/store/id/IdType.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdGenerator.java $DEST/org/neo4j/kernel/impl/store/id/IdGenerator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdGenerator.java $DEST/org/neo4j/kernel/impl/store/id/IdGenerator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdRange.java $DEST/org/neo4j/kernel/impl/store/id/IdRange.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdRange.java $DEST/org/neo4j/kernel/impl/store/id/IdRange.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdRangeIterator.java $DEST/org/neo4j/kernel/impl/store/id/IdRangeIterator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdRangeIterator.java $DEST/org/neo4j/kernel/impl/store/id/IdRangeIterator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdSequence.java $DEST/org/neo4j/kernel/impl/store/id/IdSequence.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdSequence.java $DEST/org/neo4j/kernel/impl/store/id/IdSequence.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/validation/IdValidator.java $DEST/org/neo4j/kernel/impl/store/id/validation/IdValidator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/validation/IdValidator.java $DEST/org/neo4j/kernel/impl/store/id/validation/IdValidator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/validation/ReservedIdException.java $DEST/org/neo4j/kernel/impl/store/id/validation/ReservedIdException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/validation/ReservedIdException.java $DEST/org/neo4j/kernel/impl/store/id/validation/ReservedIdException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/UnderlyingStorageException.java $DEST/org/neo4j/kernel/impl/store/UnderlyingStorageException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/UnderlyingStorageException.java $DEST/org/neo4j/kernel/impl/store/UnderlyingStorageException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreFailureException.java $DEST/org/neo4j/kernel/impl/store/StoreFailureException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreFailureException.java $DEST/org/neo4j/kernel/impl/store/StoreFailureException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/validation/NegativeIdException.java $DEST/org/neo4j/kernel/impl/store/id/validation/NegativeIdException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/validation/NegativeIdException.java $DEST/org/neo4j/kernel/impl/store/id/validation/NegativeIdException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/validation/IdCapacityExceededException.java $DEST/org/neo4j/kernel/impl/store/id/validation/IdCapacityExceededException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/validation/IdCapacityExceededException.java $DEST/org/neo4j/kernel/impl/store/id/validation/IdCapacityExceededException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/DynamicStringStore.java $DEST/org/neo4j/kernel/impl/store/DynamicStringStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/DynamicStringStore.java $DEST/org/neo4j/kernel/impl/store/DynamicStringStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/RecordFormat.java $DEST/org/neo4j/kernel/impl/store/format/RecordFormat.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/RecordFormat.java $DEST/org/neo4j/kernel/impl/store/format/RecordFormat.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreHeader.java $DEST/org/neo4j/kernel/impl/store/StoreHeader.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreHeader.java $DEST/org/neo4j/kernel/impl/store/StoreHeader.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/RecordLoad.java $DEST/org/neo4j/kernel/impl/store/record/RecordLoad.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/RecordLoad.java $DEST/org/neo4j/kernel/impl/store/record/RecordLoad.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/InvalidRecordException.java $DEST/org/neo4j/kernel/impl/store/InvalidRecordException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/InvalidRecordException.java $DEST/org/neo4j/kernel/impl/store/InvalidRecordException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/RecordStore.java $DEST/org/neo4j/kernel/impl/store/RecordStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/RecordStore.java $DEST/org/neo4j/kernel/impl/store/RecordStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/RecordCursor.java $DEST/org/neo4j/kernel/impl/store/RecordCursor.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/RecordCursor.java $DEST/org/neo4j/kernel/impl/store/RecordCursor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/RelationshipRecord.java $DEST/org/neo4j/kernel/impl/store/record/RelationshipRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/RelationshipRecord.java $DEST/org/neo4j/kernel/impl/store/record/RelationshipRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/RelationshipTypeTokenRecord.java $DEST/org/neo4j/kernel/impl/store/record/RelationshipTypeTokenRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/RelationshipTypeTokenRecord.java $DEST/org/neo4j/kernel/impl/store/record/RelationshipTypeTokenRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/TokenRecord.java $DEST/org/neo4j/kernel/impl/store/record/TokenRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/TokenRecord.java $DEST/org/neo4j/kernel/impl/store/record/TokenRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/PropertyKeyTokenRecord.java $DEST/org/neo4j/kernel/impl/store/record/PropertyKeyTokenRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/PropertyKeyTokenRecord.java $DEST/org/neo4j/kernel/impl/store/record/PropertyKeyTokenRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/LabelTokenRecord.java $DEST/org/neo4j/kernel/impl/store/record/LabelTokenRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/LabelTokenRecord.java $DEST/org/neo4j/kernel/impl/store/record/LabelTokenRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/RelationshipGroupRecord.java $DEST/org/neo4j/kernel/impl/store/record/RelationshipGroupRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/RelationshipGroupRecord.java $DEST/org/neo4j/kernel/impl/store/record/RelationshipGroupRecord.java
echo $COMMAND $SOURCE/org/neo4j/helpers/progress/ProgressListener.java $DEST/org/neo4j/helpers/progress/ProgressListener.java
$COMMAND $SOURCE/org/neo4j/helpers/progress/ProgressListener.java $DEST/org/neo4j/helpers/progress/ProgressListener.java
echo $COMMAND $SOURCE/org/neo4j/helpers/progress/Aggregator.java $DEST/org/neo4j/helpers/progress/Aggregator.java
$COMMAND $SOURCE/org/neo4j/helpers/progress/Aggregator.java $DEST/org/neo4j/helpers/progress/Aggregator.java
echo $COMMAND $SOURCE/org/neo4j/helpers/progress/Indicator.java $DEST/org/neo4j/helpers/progress/Indicator.java
$COMMAND $SOURCE/org/neo4j/helpers/progress/Indicator.java $DEST/org/neo4j/helpers/progress/Indicator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/Scanner.java $DEST/org/neo4j/kernel/impl/store/Scanner.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/Scanner.java $DEST/org/neo4j/kernel/impl/store/Scanner.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreIdIterator.java $DEST/org/neo4j/kernel/impl/store/StoreIdIterator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreIdIterator.java $DEST/org/neo4j/kernel/impl/store/StoreIdIterator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/AbstractDynamicStore.java $DEST/org/neo4j/kernel/impl/store/AbstractDynamicStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/AbstractDynamicStore.java $DEST/org/neo4j/kernel/impl/store/AbstractDynamicStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/DynamicRecordAllocator.java $DEST/org/neo4j/kernel/impl/store/DynamicRecordAllocator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/DynamicRecordAllocator.java $DEST/org/neo4j/kernel/impl/store/DynamicRecordAllocator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/LongerShortString.java $DEST/org/neo4j/kernel/impl/store/LongerShortString.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/LongerShortString.java $DEST/org/neo4j/kernel/impl/store/LongerShortString.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/util/Bits.java $DEST/org/neo4j/kernel/impl/util/Bits.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/util/Bits.java $DEST/org/neo4j/kernel/impl/util/Bits.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/ShortArray.java $DEST/org/neo4j/kernel/impl/store/ShortArray.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/ShortArray.java $DEST/org/neo4j/kernel/impl/store/ShortArray.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/GeometryType.java $DEST/org/neo4j/kernel/impl/store/GeometryType.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/GeometryType.java $DEST/org/neo4j/kernel/impl/store/GeometryType.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/DynamicArrayStore.java $DEST/org/neo4j/kernel/impl/store/DynamicArrayStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/DynamicArrayStore.java $DEST/org/neo4j/kernel/impl/store/DynamicArrayStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/RecordFormats.java $DEST/org/neo4j/kernel/impl/store/format/RecordFormats.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/RecordFormats.java $DEST/org/neo4j/kernel/impl/store/format/RecordFormats.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/Capability.java $DEST/org/neo4j/kernel/impl/store/format/Capability.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/Capability.java $DEST/org/neo4j/kernel/impl/store/format/Capability.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/CapabilityType.java $DEST/org/neo4j/kernel/impl/store/format/CapabilityType.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/CapabilityType.java $DEST/org/neo4j/kernel/impl/store/format/CapabilityType.java
echo $COMMAND $SOURCE/org/neo4j/helpers/ArrayUtil.java $DEST/org/neo4j/helpers/ArrayUtil.java
$COMMAND $SOURCE/org/neo4j/helpers/ArrayUtil.java $DEST/org/neo4j/helpers/ArrayUtil.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/FormatFamily.java $DEST/org/neo4j/kernel/impl/store/format/FormatFamily.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/FormatFamily.java $DEST/org/neo4j/kernel/impl/store/format/FormatFamily.java
echo $COMMAND $SOURCE/org/neo4j/helpers/Service.java $DEST/org/neo4j/helpers/Service.java
$COMMAND $SOURCE/org/neo4j/helpers/Service.java $DEST/org/neo4j/helpers/Service.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/TemporalType.java $DEST/org/neo4j/kernel/impl/store/TemporalType.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/TemporalType.java $DEST/org/neo4j/kernel/impl/store/TemporalType.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/UnsupportedFormatCapabilityException.java $DEST/org/neo4j/kernel/impl/store/format/UnsupportedFormatCapabilityException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/UnsupportedFormatCapabilityException.java $DEST/org/neo4j/kernel/impl/store/format/UnsupportedFormatCapabilityException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/CommonAbstractStore.java $DEST/org/neo4j/kernel/impl/store/CommonAbstractStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/CommonAbstractStore.java $DEST/org/neo4j/kernel/impl/store/CommonAbstractStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreHeaderFormat.java $DEST/org/neo4j/kernel/impl/store/StoreHeaderFormat.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreHeaderFormat.java $DEST/org/neo4j/kernel/impl/store/StoreHeaderFormat.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/InvalidIdGeneratorException.java $DEST/org/neo4j/kernel/impl/store/InvalidIdGeneratorException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/InvalidIdGeneratorException.java $DEST/org/neo4j/kernel/impl/store/InvalidIdGeneratorException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreNotFoundException.java $DEST/org/neo4j/kernel/impl/store/StoreNotFoundException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreNotFoundException.java $DEST/org/neo4j/kernel/impl/store/StoreNotFoundException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/RecordPageLocationCalculator.java $DEST/org/neo4j/kernel/impl/store/RecordPageLocationCalculator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/RecordPageLocationCalculator.java $DEST/org/neo4j/kernel/impl/store/RecordPageLocationCalculator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreRecordCursor.java $DEST/org/neo4j/kernel/impl/store/StoreRecordCursor.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/StoreRecordCursor.java $DEST/org/neo4j/kernel/impl/store/StoreRecordCursor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/IntStoreHeader.java $DEST/org/neo4j/kernel/impl/store/IntStoreHeader.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/IntStoreHeader.java $DEST/org/neo4j/kernel/impl/store/IntStoreHeader.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/IntStoreHeaderFormat.java $DEST/org/neo4j/kernel/impl/store/IntStoreHeaderFormat.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/IntStoreHeaderFormat.java $DEST/org/neo4j/kernel/impl/store/IntStoreHeaderFormat.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/StandardDynamicRecordAllocator.java $DEST/org/neo4j/kernel/impl/store/StandardDynamicRecordAllocator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/StandardDynamicRecordAllocator.java $DEST/org/neo4j/kernel/impl/store/StandardDynamicRecordAllocator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/PropertyKeyTokenStore.java $DEST/org/neo4j/kernel/impl/store/PropertyKeyTokenStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/PropertyKeyTokenStore.java $DEST/org/neo4j/kernel/impl/store/PropertyKeyTokenStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/TokenStore.java $DEST/org/neo4j/kernel/impl/store/TokenStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/TokenStore.java $DEST/org/neo4j/kernel/impl/store/TokenStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/NoStoreHeaderFormat.java $DEST/org/neo4j/kernel/impl/store/NoStoreHeaderFormat.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/NoStoreHeaderFormat.java $DEST/org/neo4j/kernel/impl/store/NoStoreHeaderFormat.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/NoStoreHeader.java $DEST/org/neo4j/kernel/impl/store/NoStoreHeader.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/NoStoreHeader.java $DEST/org/neo4j/kernel/impl/store/NoStoreHeader.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/TemporalValueWriterAdapter.java $DEST/org/neo4j/kernel/impl/store/TemporalValueWriterAdapter.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/TemporalValueWriterAdapter.java $DEST/org/neo4j/kernel/impl/store/TemporalValueWriterAdapter.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/PropertyValueRecordSizeCalculator.java $DEST/org/neo4j/kernel/impl/store/PropertyValueRecordSizeCalculator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/PropertyValueRecordSizeCalculator.java $DEST/org/neo4j/kernel/impl/store/PropertyValueRecordSizeCalculator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/BatchingIdSequence.java $DEST/org/neo4j/kernel/impl/store/id/BatchingIdSequence.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/BatchingIdSequence.java $DEST/org/neo4j/kernel/impl/store/id/BatchingIdSequence.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/NodeLabelsField.java $DEST/org/neo4j/kernel/impl/store/NodeLabelsField.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/NodeLabelsField.java $DEST/org/neo4j/kernel/impl/store/NodeLabelsField.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/NodeLabels.java $DEST/org/neo4j/kernel/impl/store/NodeLabels.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/NodeLabels.java $DEST/org/neo4j/kernel/impl/store/NodeLabels.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/NodeStore.java $DEST/org/neo4j/kernel/impl/store/NodeStore.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/NodeStore.java $DEST/org/neo4j/kernel/impl/store/NodeStore.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/DynamicNodeLabels.java $DEST/org/neo4j/kernel/impl/store/DynamicNodeLabels.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/DynamicNodeLabels.java $DEST/org/neo4j/kernel/impl/store/DynamicNodeLabels.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/LabelIdArray.java $DEST/org/neo4j/kernel/impl/store/LabelIdArray.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/LabelIdArray.java $DEST/org/neo4j/kernel/impl/store/LabelIdArray.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/InlineNodeLabels.java $DEST/org/neo4j/kernel/impl/store/InlineNodeLabels.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/InlineNodeLabels.java $DEST/org/neo4j/kernel/impl/store/InlineNodeLabels.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/allocator/ReusableRecordsCompositeAllocator.java $DEST/org/neo4j/kernel/impl/store/allocator/ReusableRecordsCompositeAllocator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/allocator/ReusableRecordsCompositeAllocator.java $DEST/org/neo4j/kernel/impl/store/allocator/ReusableRecordsCompositeAllocator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/allocator/ReusableRecordsAllocator.java $DEST/org/neo4j/kernel/impl/store/allocator/ReusableRecordsAllocator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/allocator/ReusableRecordsAllocator.java $DEST/org/neo4j/kernel/impl/store/allocator/ReusableRecordsAllocator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/state/PropertyRecordChange.java $DEST/org/neo4j/kernel/impl/transaction/state/PropertyRecordChange.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/state/PropertyRecordChange.java $DEST/org/neo4j/kernel/impl/transaction/state/PropertyRecordChange.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/schema/SchemaRule.java $DEST/org/neo4j/storageengine/api/schema/SchemaRule.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/schema/SchemaRule.java $DEST/org/neo4j/storageengine/api/schema/SchemaRule.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/IndexRule.java $DEST/org/neo4j/kernel/impl/store/record/IndexRule.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/IndexRule.java $DEST/org/neo4j/kernel/impl/store/record/IndexRule.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexProvider.java $DEST/org/neo4j/kernel/api/index/IndexProvider.java
$COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexProvider.java $DEST/org/neo4j/kernel/api/index/IndexProvider.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexDirectoryStructure.java $DEST/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
$COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexDirectoryStructure.java $DEST/org/neo4j/kernel/api/index/IndexDirectoryStructure.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingConfig.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingConfig.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingConfig.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingConfig.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexPopulator.java $DEST/org/neo4j/kernel/api/index/IndexPopulator.java
$COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexPopulator.java $DEST/org/neo4j/kernel/api/index/IndexPopulator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/index/PropertyAccessor.java $DEST/org/neo4j/kernel/api/index/PropertyAccessor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/index/PropertyAccessor.java $DEST/org/neo4j/kernel/api/index/PropertyAccessor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexUpdater.java $DEST/org/neo4j/kernel/api/index/IndexUpdater.java
$COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexUpdater.java $DEST/org/neo4j/kernel/api/index/IndexUpdater.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexEntryUpdate.java $DEST/org/neo4j/kernel/api/index/IndexEntryUpdate.java
$COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexEntryUpdate.java $DEST/org/neo4j/kernel/api/index/IndexEntryUpdate.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/UpdateMode.java $DEST/org/neo4j/kernel/impl/api/index/UpdateMode.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/UpdateMode.java $DEST/org/neo4j/kernel/impl/api/index/UpdateMode.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexEntryConflictException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexEntryConflictException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexEntryConflictException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexEntryConflictException.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/schema/IndexSample.java $DEST/org/neo4j/storageengine/api/schema/IndexSample.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/schema/IndexSample.java $DEST/org/neo4j/storageengine/api/schema/IndexSample.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/updater/SwallowingIndexUpdater.java $DEST/org/neo4j/kernel/impl/api/index/updater/SwallowingIndexUpdater.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/updater/SwallowingIndexUpdater.java $DEST/org/neo4j/kernel/impl/api/index/updater/SwallowingIndexUpdater.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexAccessor.java $DEST/org/neo4j/kernel/api/index/IndexAccessor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/index/IndexAccessor.java $DEST/org/neo4j/kernel/api/index/IndexAccessor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexUpdateMode.java $DEST/org/neo4j/kernel/impl/api/index/IndexUpdateMode.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexUpdateMode.java $DEST/org/neo4j/kernel/impl/api/index/IndexUpdateMode.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/schema/IndexReader.java $DEST/org/neo4j/storageengine/api/schema/IndexReader.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/schema/IndexReader.java $DEST/org/neo4j/storageengine/api/schema/IndexReader.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/schema/IndexSampler.java $DEST/org/neo4j/storageengine/api/schema/IndexSampler.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/schema/IndexSampler.java $DEST/org/neo4j/storageengine/api/schema/IndexSampler.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/schema/IndexProgressor.java $DEST/org/neo4j/storageengine/api/schema/IndexProgressor.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/schema/IndexProgressor.java $DEST/org/neo4j/storageengine/api/schema/IndexProgressor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/storageengine/impl/recordstorage/ExplicitIndexProgressor.java $DEST/org/neo4j/kernel/impl/storageengine/impl/recordstorage/ExplicitIndexProgressor.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/storageengine/impl/recordstorage/ExplicitIndexProgressor.java $DEST/org/neo4j/kernel/impl/storageengine/impl/recordstorage/ExplicitIndexProgressor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/index/labelscan/LabelScanValueIndexProgressor.java $DEST/org/neo4j/kernel/impl/index/labelscan/LabelScanValueIndexProgressor.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/index/labelscan/LabelScanValueIndexProgressor.java $DEST/org/neo4j/kernel/impl/index/labelscan/LabelScanValueIndexProgressor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/index/labelscan/LabelScanValueIndexAccessor.java $DEST/org/neo4j/kernel/impl/index/labelscan/LabelScanValueIndexAccessor.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/index/labelscan/LabelScanValueIndexAccessor.java $DEST/org/neo4j/kernel/impl/index/labelscan/LabelScanValueIndexAccessor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/index/labelscan/LabelScanKey.java $DEST/org/neo4j/kernel/impl/index/labelscan/LabelScanKey.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/index/labelscan/LabelScanKey.java $DEST/org/neo4j/kernel/impl/index/labelscan/LabelScanKey.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/index/labelscan/LabelScanValue.java $DEST/org/neo4j/kernel/impl/index/labelscan/LabelScanValue.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/index/labelscan/LabelScanValue.java $DEST/org/neo4j/kernel/impl/index/labelscan/LabelScanValue.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexNotApplicableKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexNotApplicableKernelException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexNotApplicableKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexNotApplicableKernelException.java
echo $COMMAND $SOURCE/org/neo4j/helpers/collection/BoundedIterable.java $DEST/org/neo4j/helpers/collection/BoundedIterable.java
$COMMAND $SOURCE/org/neo4j/helpers/collection/BoundedIterable.java $DEST/org/neo4j/helpers/collection/BoundedIterable.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/storemigration/StoreMigrationParticipant.java $DEST/org/neo4j/kernel/impl/storemigration/StoreMigrationParticipant.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/storemigration/StoreMigrationParticipant.java $DEST/org/neo4j/kernel/impl/storemigration/StoreMigrationParticipant.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/util/monitoring/ProgressReporter.java $DEST/org/neo4j/kernel/impl/util/monitoring/ProgressReporter.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/util/monitoring/ProgressReporter.java $DEST/org/neo4j/kernel/impl/util/monitoring/ProgressReporter.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/storemigration/participant/AbstractStoreMigrationParticipant.java $DEST/org/neo4j/kernel/impl/storemigration/participant/AbstractStoreMigrationParticipant.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/storemigration/participant/AbstractStoreMigrationParticipant.java $DEST/org/neo4j/kernel/impl/storemigration/participant/AbstractStoreMigrationParticipant.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/SchemaRuleSerialization.java $DEST/org/neo4j/kernel/impl/store/record/SchemaRuleSerialization.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/SchemaRuleSerialization.java $DEST/org/neo4j/kernel/impl/store/record/SchemaRuleSerialization.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/ConstraintRule.java $DEST/org/neo4j/kernel/impl/store/record/ConstraintRule.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/ConstraintRule.java $DEST/org/neo4j/kernel/impl/store/record/ConstraintRule.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/UniquenessConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/UniquenessConstraintDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/UniquenessConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/UniquenessConstraintDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/NodeKeyConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/NodeKeyConstraintDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/NodeKeyConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/NodeKeyConstraintDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/schema/MalformedSchemaRuleException.java $DEST/org/neo4j/kernel/api/exceptions/schema/MalformedSchemaRuleException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/schema/MalformedSchemaRuleException.java $DEST/org/neo4j/kernel/api/exceptions/schema/MalformedSchemaRuleException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/SchemaRuleDeserializer2_0to3_1.java $DEST/org/neo4j/kernel/impl/store/record/SchemaRuleDeserializer2_0to3_1.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/SchemaRuleDeserializer2_0to3_1.java $DEST/org/neo4j/kernel/impl/store/record/SchemaRuleDeserializer2_0to3_1.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/ConstraintDescriptorFactory.java $DEST/org/neo4j/kernel/api/schema/constaints/ConstraintDescriptorFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/ConstraintDescriptorFactory.java $DEST/org/neo4j/kernel/api/schema/constaints/ConstraintDescriptorFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/NodeExistenceConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/NodeExistenceConstraintDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/NodeExistenceConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/NodeExistenceConstraintDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/RelExistenceConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/RelExistenceConstraintDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/api/schema/constaints/RelExistenceConstraintDescriptor.java $DEST/org/neo4j/kernel/api/schema/constaints/RelExistenceConstraintDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/SchemaRecord.java $DEST/org/neo4j/kernel/impl/store/record/SchemaRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/SchemaRecord.java $DEST/org/neo4j/kernel/impl/store/record/SchemaRecord.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/StorageCommand.java $DEST/org/neo4j/storageengine/api/StorageCommand.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/StorageCommand.java $DEST/org/neo4j/storageengine/api/StorageCommand.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/NeoStoreRecord.java $DEST/org/neo4j/kernel/impl/store/record/NeoStoreRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/NeoStoreRecord.java $DEST/org/neo4j/kernel/impl/store/record/NeoStoreRecord.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/util/IdPrettyPrinter.java $DEST/org/neo4j/kernel/impl/util/IdPrettyPrinter.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/util/IdPrettyPrinter.java $DEST/org/neo4j/kernel/impl/util/IdPrettyPrinter.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/CommandReaderFactory.java $DEST/org/neo4j/storageengine/api/CommandReaderFactory.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/CommandReaderFactory.java $DEST/org/neo4j/storageengine/api/CommandReaderFactory.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/CommandReader.java $DEST/org/neo4j/storageengine/api/CommandReader.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/CommandReader.java $DEST/org/neo4j/storageengine/api/CommandReader.java
echo $COMMAND $SOURCE/org/neo4j/kernel/info/DiagnosticsManager.java $DEST/org/neo4j/kernel/info/DiagnosticsManager.java
$COMMAND $SOURCE/org/neo4j/kernel/info/DiagnosticsManager.java $DEST/org/neo4j/kernel/info/DiagnosticsManager.java
echo $COMMAND $SOURCE/org/neo4j/kernel/info/DiagnosticsExtractor.java $DEST/org/neo4j/kernel/info/DiagnosticsExtractor.java
$COMMAND $SOURCE/org/neo4j/kernel/info/DiagnosticsExtractor.java $DEST/org/neo4j/kernel/info/DiagnosticsExtractor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/info/SystemDiagnostics.java $DEST/org/neo4j/kernel/info/SystemDiagnostics.java
$COMMAND $SOURCE/org/neo4j/kernel/info/SystemDiagnostics.java $DEST/org/neo4j/kernel/info/SystemDiagnostics.java
echo $COMMAND $SOURCE/org/neo4j/helpers/Format.java $DEST/org/neo4j/helpers/Format.java
$COMMAND $SOURCE/org/neo4j/helpers/Format.java $DEST/org/neo4j/helpers/Format.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/standard/StandardFormatSettings.java $DEST/org/neo4j/kernel/impl/store/format/standard/StandardFormatSettings.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/standard/StandardFormatSettings.java $DEST/org/neo4j/kernel/impl/store/format/standard/StandardFormatSettings.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdGeneratorImpl.java $DEST/org/neo4j/kernel/impl/store/id/IdGeneratorImpl.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdGeneratorImpl.java $DEST/org/neo4j/kernel/impl/store/id/IdGeneratorImpl.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdContainer.java $DEST/org/neo4j/kernel/impl/store/id/IdContainer.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/IdContainer.java $DEST/org/neo4j/kernel/impl/store/id/IdContainer.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/FreeIdKeeper.java $DEST/org/neo4j/kernel/impl/store/id/FreeIdKeeper.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/id/FreeIdKeeper.java $DEST/org/neo4j/kernel/impl/store/id/FreeIdKeeper.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/command/NeoCommandType.java $DEST/org/neo4j/kernel/impl/transaction/command/NeoCommandType.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/command/NeoCommandType.java $DEST/org/neo4j/kernel/impl/transaction/command/NeoCommandType.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/StatementConstants.java $DEST/org/neo4j/kernel/api/StatementConstants.java
$COMMAND $SOURCE/org/neo4j/kernel/api/StatementConstants.java $DEST/org/neo4j/kernel/api/StatementConstants.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/util/Validator.java $DEST/org/neo4j/kernel/impl/util/Validator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/util/Validator.java $DEST/org/neo4j/kernel/impl/util/Validator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/configuration/Title.java $DEST/org/neo4j/kernel/configuration/Title.java
$COMMAND $SOURCE/org/neo4j/kernel/configuration/Title.java $DEST/org/neo4j/kernel/configuration/Title.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/standard/PropertyRecordFormat.java $DEST/org/neo4j/kernel/impl/store/format/standard/PropertyRecordFormat.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/standard/PropertyRecordFormat.java $DEST/org/neo4j/kernel/impl/store/format/standard/PropertyRecordFormat.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/BaseRecordFormat.java $DEST/org/neo4j/kernel/impl/store/format/BaseRecordFormat.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/format/BaseRecordFormat.java $DEST/org/neo4j/kernel/impl/store/format/BaseRecordFormat.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/MetaDataRecord.java $DEST/org/neo4j/kernel/impl/store/record/MetaDataRecord.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/record/MetaDataRecord.java $DEST/org/neo4j/kernel/impl/store/record/MetaDataRecord.java
echo $COMMAND $SOURCE/org/neo4j/storageengine/api/StoreFileMetadata.java $DEST/org/neo4j/storageengine/api/StoreFileMetadata.java
$COMMAND $SOURCE/org/neo4j/storageengine/api/StoreFileMetadata.java $DEST/org/neo4j/storageengine/api/StoreFileMetadata.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexingService.java $DEST/org/neo4j/kernel/impl/api/index/IndexingService.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexingService.java $DEST/org/neo4j/kernel/impl/api/index/IndexingService.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProxyCreator.java $DEST/org/neo4j/kernel/impl/api/index/IndexProxyCreator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProxyCreator.java $DEST/org/neo4j/kernel/impl/api/index/IndexProxyCreator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexStoreView.java $DEST/org/neo4j/kernel/impl/api/index/IndexStoreView.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexStoreView.java $DEST/org/neo4j/kernel/impl/api/index/IndexStoreView.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/StoreScan.java $DEST/org/neo4j/kernel/impl/api/index/StoreScan.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/StoreScan.java $DEST/org/neo4j/kernel/impl/api/index/StoreScan.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/MultipleIndexPopulator.java $DEST/org/neo4j/kernel/impl/api/index/MultipleIndexPopulator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/MultipleIndexPopulator.java $DEST/org/neo4j/kernel/impl/api/index/MultipleIndexPopulator.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexMeta.java $DEST/org/neo4j/kernel/impl/api/index/IndexMeta.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexMeta.java $DEST/org/neo4j/kernel/impl/api/index/IndexMeta.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/FlippableIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/FlippableIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/FlippableIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/FlippableIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/IndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/IndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexPopulationFailure.java $DEST/org/neo4j/kernel/impl/api/index/IndexPopulationFailure.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexPopulationFailure.java $DEST/org/neo4j/kernel/impl/api/index/IndexPopulationFailure.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexPopulationFailedKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexPopulationFailedKernelException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexPopulationFailedKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexPopulationFailedKernelException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexActivationFailedKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexActivationFailedKernelException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexActivationFailedKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexActivationFailedKernelException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/schema/UniquePropertyValueValidationException.java $DEST/org/neo4j/kernel/api/exceptions/schema/UniquePropertyValueValidationException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/schema/UniquePropertyValueValidationException.java $DEST/org/neo4j/kernel/api/exceptions/schema/UniquePropertyValueValidationException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProxyFactory.java $DEST/org/neo4j/kernel/impl/api/index/IndexProxyFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProxyFactory.java $DEST/org/neo4j/kernel/impl/api/index/IndexProxyFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/FailedIndexProxyFactory.java $DEST/org/neo4j/kernel/impl/api/index/FailedIndexProxyFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/FailedIndexProxyFactory.java $DEST/org/neo4j/kernel/impl/api/index/FailedIndexProxyFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/updater/DelegatingIndexUpdater.java $DEST/org/neo4j/kernel/impl/api/index/updater/DelegatingIndexUpdater.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/updater/DelegatingIndexUpdater.java $DEST/org/neo4j/kernel/impl/api/index/updater/DelegatingIndexUpdater.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/FlipFailedKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/FlipFailedKernelException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/FlipFailedKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/FlipFailedKernelException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/ExceptionDuringFlipKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/ExceptionDuringFlipKernelException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/ExceptionDuringFlipKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/ExceptionDuringFlipKernelException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexProxyAlreadyClosedKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexProxyAlreadyClosedKernelException.java
$COMMAND $SOURCE/org/neo4j/kernel/api/exceptions/index/IndexProxyAlreadyClosedKernelException.java $DEST/org/neo4j/kernel/api/exceptions/index/IndexProxyAlreadyClosedKernelException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexCountsRemover.java $DEST/org/neo4j/kernel/impl/api/index/IndexCountsRemover.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexCountsRemover.java $DEST/org/neo4j/kernel/impl/api/index/IndexCountsRemover.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/FailedIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/FailedIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/FailedIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/FailedIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/AbstractSwallowingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/AbstractSwallowingIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/AbstractSwallowingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/AbstractSwallowingIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/BatchingMultipleIndexPopulator.java $DEST/org/neo4j/kernel/impl/api/index/BatchingMultipleIndexPopulator.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/BatchingMultipleIndexPopulator.java $DEST/org/neo4j/kernel/impl/api/index/BatchingMultipleIndexPopulator.java
echo $COMMAND $SOURCE/org/neo4j/helpers/NamedThreadFactory.java $DEST/org/neo4j/helpers/NamedThreadFactory.java
$COMMAND $SOURCE/org/neo4j/helpers/NamedThreadFactory.java $DEST/org/neo4j/helpers/NamedThreadFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexPopulationJob.java $DEST/org/neo4j/kernel/impl/api/index/IndexPopulationJob.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexPopulationJob.java $DEST/org/neo4j/kernel/impl/api/index/IndexPopulationJob.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/SchemaState.java $DEST/org/neo4j/kernel/impl/api/SchemaState.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/SchemaState.java $DEST/org/neo4j/kernel/impl/api/SchemaState.java
echo $COMMAND $SOURCE/org/neo4j/helpers/FutureAdapter.java $DEST/org/neo4j/helpers/FutureAdapter.java
$COMMAND $SOURCE/org/neo4j/helpers/FutureAdapter.java $DEST/org/neo4j/helpers/FutureAdapter.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/NodeUpdates.java $DEST/org/neo4j/kernel/impl/api/index/NodeUpdates.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/NodeUpdates.java $DEST/org/neo4j/kernel/impl/api/index/NodeUpdates.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/PropertyLoader.java $DEST/org/neo4j/kernel/impl/api/index/PropertyLoader.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/PropertyLoader.java $DEST/org/neo4j/kernel/impl/api/index/PropertyLoader.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProviderMap.java $DEST/org/neo4j/kernel/impl/api/index/IndexProviderMap.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProviderMap.java $DEST/org/neo4j/kernel/impl/api/index/IndexProviderMap.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProviderNotFoundException.java $DEST/org/neo4j/kernel/impl/api/index/IndexProviderNotFoundException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexProviderNotFoundException.java $DEST/org/neo4j/kernel/impl/api/index/IndexProviderNotFoundException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/PopulatingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/PopulatingIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/PopulatingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/PopulatingIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/OnlineIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/OnlineIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/OnlineIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/OnlineIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/updater/UpdateCountingIndexUpdater.java $DEST/org/neo4j/kernel/impl/api/index/updater/UpdateCountingIndexUpdater.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/updater/UpdateCountingIndexUpdater.java $DEST/org/neo4j/kernel/impl/api/index/updater/UpdateCountingIndexUpdater.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/FailedPopulatingIndexProxyFactory.java $DEST/org/neo4j/kernel/impl/api/index/FailedPopulatingIndexProxyFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/FailedPopulatingIndexProxyFactory.java $DEST/org/neo4j/kernel/impl/api/index/FailedPopulatingIndexProxyFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/ContractCheckingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/ContractCheckingIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/ContractCheckingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/ContractCheckingIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/DelegatingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/DelegatingIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/DelegatingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/DelegatingIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/AbstractDelegatingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/AbstractDelegatingIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/AbstractDelegatingIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/AbstractDelegatingIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/RecoveringIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/RecoveringIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/RecoveringIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/RecoveringIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/TentativeConstraintIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/TentativeConstraintIndexProxy.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/TentativeConstraintIndexProxy.java $DEST/org/neo4j/kernel/impl/api/index/TentativeConstraintIndexProxy.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/index/schema/DeferredConflictCheckingIndexUpdater.java $DEST/org/neo4j/kernel/impl/index/schema/DeferredConflictCheckingIndexUpdater.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/index/schema/DeferredConflictCheckingIndexUpdater.java $DEST/org/neo4j/kernel/impl/index/schema/DeferredConflictCheckingIndexUpdater.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexMapReference.java $DEST/org/neo4j/kernel/impl/api/index/IndexMapReference.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexMapReference.java $DEST/org/neo4j/kernel/impl/api/index/IndexMapReference.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexMap.java $DEST/org/neo4j/kernel/impl/api/index/IndexMap.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexMap.java $DEST/org/neo4j/kernel/impl/api/index/IndexMap.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexUpdaterMap.java $DEST/org/neo4j/kernel/impl/api/index/IndexUpdaterMap.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexUpdaterMap.java $DEST/org/neo4j/kernel/impl/api/index/IndexUpdaterMap.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/store/MultipleUnderlyingStorageExceptions.java $DEST/org/neo4j/kernel/impl/store/MultipleUnderlyingStorageExceptions.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/store/MultipleUnderlyingStorageExceptions.java $DEST/org/neo4j/kernel/impl/store/MultipleUnderlyingStorageExceptions.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexMapSnapshotProvider.java $DEST/org/neo4j/kernel/impl/api/index/IndexMapSnapshotProvider.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexMapSnapshotProvider.java $DEST/org/neo4j/kernel/impl/api/index/IndexMapSnapshotProvider.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingController.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingController.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingController.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingController.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobFactory.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobFactory.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJob.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJob.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJob.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJob.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobQueue.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobQueue.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobQueue.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobQueue.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobTracker.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobTracker.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobTracker.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingJobTracker.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingMode.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingMode.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingMode.java $DEST/org/neo4j/kernel/impl/api/index/sampling/IndexSamplingMode.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/MultiPopulatorFactory.java $DEST/org/neo4j/kernel/impl/api/index/MultiPopulatorFactory.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/MultiPopulatorFactory.java $DEST/org/neo4j/kernel/impl/api/index/MultiPopulatorFactory.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/state/IndexUpdates.java $DEST/org/neo4j/kernel/impl/transaction/state/IndexUpdates.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/transaction/state/IndexUpdates.java $DEST/org/neo4j/kernel/impl/transaction/state/IndexUpdates.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/RebuildingIndexDescriptor.java $DEST/org/neo4j/kernel/impl/api/index/RebuildingIndexDescriptor.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/RebuildingIndexDescriptor.java $DEST/org/neo4j/kernel/impl/api/index/RebuildingIndexDescriptor.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexingUpdateService.java $DEST/org/neo4j/kernel/impl/api/index/IndexingUpdateService.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexingUpdateService.java $DEST/org/neo4j/kernel/impl/api/index/IndexingUpdateService.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexPopulationJobController.java $DEST/org/neo4j/kernel/impl/api/index/IndexPopulationJobController.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/api/index/IndexPopulationJobController.java $DEST/org/neo4j/kernel/impl/api/index/IndexPopulationJobController.java
echo $COMMAND $SOURCE/org/neo4j/kernel/impl/util/UnsatisfiedDependencyException.java $DEST/org/neo4j/kernel/impl/util/UnsatisfiedDependencyException.java
$COMMAND $SOURCE/org/neo4j/kernel/impl/util/UnsatisfiedDependencyException.java $DEST/org/neo4j/kernel/impl/util/UnsatisfiedDependencyException.java
echo $COMMAND $SOURCE/org/neo4j/kernel/api/labelscan/NodeLabelUpdate.java $DEST/org/neo4j/kernel/api/labelscan/NodeLabelUpdate.java
$COMMAND $SOURCE/org/neo4j/kernel/api/labelscan/NodeLabelUpdate.java $DEST/org/neo4j/kernel/api/labelscan/NodeLabelUpdate.java
